USE stepforward_db;

insert into Classes (title, speaker, details, current, max) values("로마서 12장 \"그리스도인 되기\"", "연규운 목사", "로마서 12장을 통해 예수 그리스도를 따르는 제자는 하나님의 놀라우신\n 은혜로 관계를 맺어 다섯 가지 구체적인 관계 속에서 그리스도인의\n 삶을 살아가는 자임을 배우게 될 것이다.", 0, 30);
insert into Classes (title, speaker, details, current, max) values("디아스포라 선교로서의 유학생 사역", "윤남근 간사", "전 세계가 지구촌화 됨에 따라 더 나은 삶을 찾아 떠나는 자발적인\n 이주민과 유학생 그리고 전쟁과 기근 등 핍박을 피해 떠나는 난민이\n 발생함에 따라 디아스포라 선교의 가능성이 증폭되고 있는 현실이다.\n 이에 본 강의에서는 디아스포라 선교로서의 유학생 사역의 중요성과\n 선교 전략적 대안을 함께 수립해 보고자 한다", 0, 30);
insert into Classes (title, speaker, details, current, max) values("나는 평생순장으로 살고싶다", "박대희 순장", "어떤 이들은 졸업 이후에 순장의 삶을 살아가기가 어렵다고 말한다.\n 그러나 그렇지 않다. 그 풍성하고 가치있는 평생순장의 삶에 대해\n 캠퍼스 순장에게 필요한 현실적인 조언과 더불이 이야기를 나누고자 한다.", 0, 30);
insert into Classes (title, speaker, details, current, max) values("취업전략", "김기열 교수", "꿈을 향해 달려가는 모든 청년들의 목마름을 해결하는 시간!", 0, 30);
insert into Classes (title, speaker, details, current, max) values("찬양 작곡을 위한 왕 기초 음악이론\n(5선 악보를 읽고 피아노 치실 수 있는분)", "강성철 간사", "ccm? 성가고? 연주곡? 클래식?\n장르는 다르지만 작곡하기에 필요한 기초음악이론", 0, 20);
insert into Classes (title, speaker, details, current, max) values("구약과 신약의 다리 \"언약\"", "최종원  간사", "성경에 나오는 언약을 중점으로 구약을 한눈에 보고,\n 신약과의 연관성 알아보기", 0, 20);
insert into Classes (title, speaker, details, current, max) values("디모데후서로 본 순장의 삶!", "김수진 간사", "예수님 다음으로 닮아야 할 순장의 모델, 바울은 어떤 순장이었을까?", 0, 20);
insert into Classes (title, speaker, details, current, max) values("아티스트 웨이", "김종철 간사", "내 안에 잠재된 창조성 회복을 위한 시간", 0, 20);
insert into Classes (title, speaker, details, current, max) values("광야에서 드리는 고백 (feat. 욥의 이야기)", "김인아 간사", "광야와 같은 시간을 보낼 때 떠오르는 가장 큰 질문,\n\"왜 이런 고난을 겪는가?\"에 대해\n 욥기서의 큰 주제를 중심으로 이야기해보고자 한다.", 0, 20);
insert into Classes (title, speaker, details, current, max) values("NK의 현실과 탈북민 선교", "신정호 간사", "북한은 같은 민족이며 우리가 알아야 하고 기도해야 할 우리나라입니다.\n 북한의 현재 상황, 탈북민의 이야기, 지금 할 수 있는 선교와 기도는\n 무엇인지 함께 알아갑시다", 0, 20);
insert into Classes (title, speaker, details, current, max) values("\"난 순장인데 왜 안 행복하지?\"", "진인엽, 박종필 간사", "행복한 순장의 삶을 살고 싶은 사람, 순장이 뭘까 고민되는 사람!", 0, 30);
insert into Classes (title, speaker, details, current, max) values("늬 하나님의 뜻을 아이 모르니?", "이동수 간사", "하나님의 뜻을 알아가고 발견하는 방법을 이해하는 시간", 0, 20);
insert into Classes (title, speaker, details, current, max) values("경청 한 잔 할래요?", "양진웅 간사", "", 0, 20);
insert into Classes (title, speaker, details, current, max) values("늘 괜찮다 말하는 당신에게", "최새로미 간사", "", 0, 20);
insert into Classes (title, speaker, details, current, max) values("고딩? 어 순원! (신입생 트렌드 알아보기)", "박구연 간사", "어떻게 하면 오늘날 청소년들의 마음의 문을 열 수 있을까를 함께\n 고민해보는 시간!", 0, 20);
insert into Classes (title, speaker, details, current, max) values("동상이몽 너는 내 운명\n (커플이 함께 참여해주세요)", "김선화, 손요섭 간사", "남자의 눈으로 바라본 여자! 여자의 눈으로 바라본 남자!\n 커플들이 겪게 되는 어려움을 함께 고민해보는 시간", 0, 30);
insert into Classes (title, speaker, details, current, max) values("마음지키기 & 동기부여하기", "최호성 간사", "느헤미야서를 통해 마음이 흔들릴 때, 동기부여가 필요할 때\n 어떻게 할지 배워보고 싶은 사람!", 0, 20);
insert into Classes (title, speaker, details, current, max) values("나 너 전도 안해!", "이시온 간사", "개독교라 불리는 시대, 전도가 싫은 전도가 어려운 사람들 다 모여라", 0, 20);
insert into Classes (title, speaker, details, current, max) values("트라우마 극복하기", "이예찬 간사", "내가 겪고 있는 문제가 혹시 트라우마는 아닌지?\n 트라우마에 대해 제대로 알고 건강하게 극복하는 방법!", 0, 20);
insert into Classes (title, speaker, details, current, max) values("게.사.모(게으른 사람들의 모임)\n 좋은 습관 만들기 프로젝트", "하예나 간사", "나의 대적, 게으름에 대해 바로 알기. 구체적 Action point 세우기.\n 세운 목표를 습관화 시키도록 한달동안 카톡방 운영예정.", 0, 20);
insert into Classes (title, speaker, details, current, max) values("어서와! 군틴트는 처음이지?", "김성도 간사", "하나님 나라의 진짜 사나이! 군대는 어떤 곳일까?\n 나의 군생활을 디자인해보고, 신앙을 지키기 위해 함께 고민해보는 시간!\n (군입대를 앞둔 형제들)", 0, 20);
insert into Classes (title, speaker, details, current, max) values("선교를 보는 눈 넓히기 MK(Missionary Kids)", "강은지 간사", "선교사의 삶의 한 부분, 선교사 자녀를 위한 MK사역,\n MK가 누군지 모르는 순장순원 모여라!", 0, 20);
insert into Classes (title, speaker, details, current, max) values("나를 사랑하지 못하는 이유.. 자존감", "김윤경 간사", "왜 나를 사랑하지 못하니? 하나님의 자녀로 자존감 upup!\n 나를 사랑하는 법 배우기", 0, 20);
insert into Classes (title, speaker, details, current, max) values("7 Ways to find the Vision", "방시리 간사", "", 0, 20);

insert into Bible (title, speaker, location, current, max) values("기독교 역사 (세계 교회사)", "임수빈 간사", "체육관 204", 0, 60);
insert into Bible (title, speaker, location, current, max) values("기독교 세계관", "현지식 목사", "바울 성전", 0, 80);
insert into Bible (title, speaker, location, current, max) values("느헤미야를 통해 본 리더십", "이봉희 간사", "체육관 102", 0, 60);
insert into Bible (title, speaker, location, current, max) values("크리스천 비전스쿨", "김훈중 목사", "베드로 성전", 0, 90);
insert into Bible (title, speaker, location, current, max) values("행복하게 잘 지내는 방법", "장세영 간사", "집회장", 0, 150);
insert into Bible (title, speaker, location, current, max) values("성서 지리", "조신형 간사", "식당 1층", 0, 60);